language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
script: python tests/all_tests.py
deploy:
  provider: pypi
  password:
    secure: "toSGwKdSbHW2NkZrQ9/XokL9bWlSYe7ziUBUhE6/8TXlSE9bIUbjEC6oJny43FCG8pZC77C3hkSyULjq8fSZyUGNqWTkpgSv+9CLsmo0PHGJbNsSGDxL3oatJ63yR+5jBdFhaSxI16Bw/AQSoFHhlL/+biJTAhO2uO+BDyUFD5o="
  user: d0c.s4vage
  on:
    tags: true
